PATTERNS = {
    "arc": [
        ("{question}\n\n{options_}", "{answer}"),
        ("Question: {question}\n\nAnswer:\n{options_}", "{answer}"),
        ("Question: {question}\n\nWhat is the correct answer to the question from the following choices?\n{options_}", "{answer}"),
        ("Q: {question}\nWhat is the correct answer to this question?\n{options_}", "{answer}"),
        ("What is the answer?\n\n{question}\n\n{options_}", "{answer}"),
        ("Answer the question\n\n{question}\n\n{options_}", "{answer}"),
        ("{question}\n\nPick the answer from these options\n\n{options_}", "{answer}"),
        ("Write a question you would see in a school textbook.", "{question}"),
        ("What's an example of a grad-school level question?", "{question}"),
        ("I just took a test in school today. What question was I asked?", "{question}"),
    ],
    "rte": [
        ("{premise}\n\nBased on the paragraph above can we conclude that \"{hypothesis}\"?\n\n{options_}", "{answer}"),
        ("{premise}\n\nBased on that paragraph can we conclude that this sentence is true?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{premise}\n\nCan we draw the following conclusion?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{premise}\nDoes this next sentence follow, given the preceding text?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{premise}\nCan we infer the following?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("Read the following paragraph and determine if the hypothesis is true:\n\n{premise}\n\nHypothesis: {hypothesis}n\n{options_}", "{answer}"),
        ("Read the text and determine if the sentence is true:\n\n{premise}\n\nSentence: {hypothesis}n\n{options_}", "{answer}"),
        ("Can we draw the following hypothesis from the context? \n\nContext:\n\n{premise}\n\nHypothesis: {hypothesis}n\n{options_}", "{answer}"),
        ("Determine if the sentence is true based on the text below:\n{hypothesis}\n\n{premise}\n{options_}", "{answer}"),
        ("Generate a context and a hypothesis.", "Context: {premise}\n\nHypothesis: {hypothesis}"),
    ],
    "boolq": [
        ("{text}\n\nCan we conclude that {question}?\n\n{options_}", "{answer}"),
        ("{text}\n\nIs it true that {question}?\n\n{options_}", "{answer}"),
        ("{text}\n\n{question}?\n\n{options_}", "{answer}"),
        ("Text: {text}\n\nQuestion: {question}?\n\n{options_}", "{answer}"),
        ("{text}\n\nWhat's the best answer to this question: {question}?\n\n{options_}", "{answer}"),
        ("{text}\nBased on the above text, what's the best answer to this question: {question}?\n\n{options_}", "{answer}"),
        ("{text}\nAnswer this question, making sure that the answer is supposed by the text: {question}?\n\n{options_}", "{answer}"),
        ("{text}\n\nIs the following statement correct based on the text\n\n{question}\n\n{options_}", "{answer}"),
        ("Is it true that {question} based on the following text?\n\n{text}\n\n{options_}", "{answer}"),
    ],
    "hellaswag": [
        ("What happens next in this paragraph?\n\n{context}\n{options_}", "{answer}"),
        ("Continue writing the next sentence in this paragraph:\n\n{context}\n\n{options_}", "{answer}"),
        ("Continue writing the next sentence.\n\n{context}\n\n{options_}", "{answer}"),
        ("This is a test of commonsense. Complete the next sentence:\n\n{context}\n\n{options_}", "{answer}"),
        ("Write the next sentence in this paragraph:\n\n{context}\n\n{options_}", "{answer}"),
        ("How does the next paragraph end?\n\n{context}\n\n{options_}", "{answer}"),
        ("What most naturally follows?\n\n{context}\n\n{options_}", "{answer}"),
        ("What happens next?\n\n{context}\n\n{options_}", "{answer}"),
        ("What is the most logical next event?\n\n{context}\n\n{options_}", "{answer}"),
        ("Write the next sentence in the following story.\n\n{context}\n\n{options_}", "{answer}"),
    ],
    "winogrande": [
        ("How does the sentence end?\n\n{context}\n\n{options_}", "{answer}"),
        ("Write the next sentence.\n\n{context}\n\n{options_}", "{answer}"),
        ("Continue the following story.\n\n{context}\n\n{options_}", "{answer}"),
        ("Complete the following sentence.\n\n{context}\n\n{options_}", "{answer}"),
        ("Continue writing the following text.\n\n{context}\n\n{options_}", "{answer}"),
        ("How does the sentence end?\n\n{context}", "{answer}"),
        ("Write the next sentence.\n\n{context}", "{answer}"),
        ("Continue the following story.\n\n{context}", "{answer}"),
        ("Complete the following sentence.\n\n{context}", "{answer}"),
        ("Continue writing the following text.\n\n{context}", "{answer}"),
    ],
    "openbookqa": [
        ("{fact}\n{question}\n\n{options_}", "{answer}"),
        ("Read this fact: \"{fact}\"\n\nNow answer this question: \"{question}\"\n\n{options_}", "{answer}"),
        ("Given the fact \"{fact}\", what is the answer to the question or completion \"{question}\"\n\n{options_}", "{answer}"),
        ("Knowing that \"{fact}\", how would one answer \"{question}\"\n\n{options_}", "{answer}"),
        ("Use evidence from the fact that {fact} to answer this question: \"{question}\"\n\n{options_}", "{answer}"),
        ("Fact: {fact}\nQuestion: {question}\n\nWhat's the answer?\n\n{options_}", "{answer}"),
        ("Use this fact to answer the question: {fact}\n\n{question}\n\n{options_}", "{answer}"),
        ("What sentence would provide a factual answer to this question: \"{question}\"", "{fact}"),
        ("What is a random fact?", "{fact}"),
        ("Generate a sentence that contains a fact.", "{fact}"),
    ],
    "piqa": [
        ("Here is a goal: {goal}\n\nHow would you accomplish this goal?\n\n{options_}", "{answer}"),
        ("Here is a goal: {goal}\n\nWhich way makes more sense to accomplish this goal?\n\n{options_}", "{answer}"),
        ("Goal: {goal}\n\nWhich of the following methods is more reasonable for accomplishing this goal?\n\n{options_}", "{answer}"),
        ("Objective: {goal}\n\nWhich of the following solutions is more sound in terms of naive physics reasoning?\n\n{options_}", "{answer}"),
        ("How do you do this: {goal}\n\n{options_}", "{answer}"),
        ("What is the best way to: {goal}\n\n{options_}", "{answer}"),
        ("Which of the following solutions is better for the following goal:\n{goal}\n\n{options_}", "{answer}"),
        ("How would someone go about accomplishing this goal?\n{goal}\n\n{options_}", "{answer}"),
        ("What's an example of a task that requires knowledge of physical objects to perform?", "{goal}"),
        ("What kind of task would test someone's ability to perform physical reasoning?", "{goal}"),
    ],
}

PATTERNS_OPTIONS = {
    "arc": [
        ("{question}\n\n{options_}", "{answer}"),
        ("Question: {question}\n\nAnswer:\n{options_}", "{answer}"),
        ("Question: {question}\n\nWhat is the correct answer to the question from the following choices?\n{options_}", "{answer}"),
        ("Q: {question}\nWhat is the correct answer to this question?\n{options_}", "{answer}"),
        ("What is the answer?\n\n{question}\n\n{options_}", "{answer}"),
        ("Answer the question\n\n{question}\n\n{options_}", "{answer}"),
        ("{question}\n\nPick the answer from these options\n\n{options_}", "{answer}"),
        ("Answer this:\n{question}\n\n{options_}", "{answer}"),
        ("Provide the correct response:\n{question}\n\n{options_}", "{answer}"),
        ("{question}\n\n{options_}Reply:", "{answer}"),
        ("What is the answer to: {question}\n\n{options_}", "{answer}"),
    ],
    "openbookqa": [
        ("{fact}\n{question}\n\n{options_}", "{answer}"),
        ("Read this fact: \"{fact}\"\n\nNow answer this question: \"{question}\"\n\n{options_}", "{answer}"),
        ("Given the fact \"{fact}\", what is the answer to the question or completion \"{question}\"\n\n{options_}", "{answer}"),
        ("Knowing that \"{fact}\", how would one answer \"{question}\"\n\n{options_}", "{answer}"),
        ("Use evidence from the fact that {fact} to answer this question: \"{question}\"\n\n{options_}", "{answer}"),
        ("Fact: {fact}\nQuestion: {question}\n\nWhat's the answer?\n\n{options_}", "{answer}"),
        ("Use this fact to answer the question: {fact}\n\n{question}\n\n{options_}", "{answer}"),
    ],
    "piqa": [
        ("Here is a goal: {goal}\n\nHow would you accomplish this goal?\n\n{options_}", "{answer}"),
        ("Here is a goal: {goal}\n\nWhich way makes more sense to accomplish this goal?\n\n{options_}", "{answer}"),
        ("Goal: {goal}\n\nWhich of the following methods is more reasonable for accomplishing this goal?\n\n{options_}", "{answer}"),
        ("Objective: {goal}\n\nWhich of the following solutions is more sound in terms of naive physics reasoning?\n\n{options_}", "{answer}"),
        ("How do you do this: {goal}\n\n{options_}", "{answer}"),
        ("What is the best way to: {goal}\n\n{options_}", "{answer}"),
        ("Which of the following solutions is better for the following goal:\n{goal}\n\n{options_}", "{answer}"),
        ("How would someone go about accomplishing this goal?\n{goal}\n\n{options_}", "{answer}"),
    ],
    "sst2": [
        ("Review:\n{sentence}\nIs this movie review sentence negative or positive?\n{options_}", "{answer}"),
        ("Short movie review: {sentence}\nDid the critic thinking positively or negatively of the movie?\n{options_}", "{answer}"),
        ("Sentence from a movie review: {sentence}\nWas the movie seen positively or negatively based on the preceding review?\n\n{options_}", "{answer}"),
        ("\"{sentence}\"\nHow would the sentiment of this sentence be perceived?\n\n{options_}", "{answer}"),
        ("Is the sentiment of the following sentence positive or negative?\n{sentence}\n{options_}", "{answer}"),
        ("What is the sentiment of the following movie review sentence?\n{sentence}\n{options_}", "{answer}"),
        ("Would the following phrase be considered positive or negative?\n\n{sentence}\n{options_}", "{answer}"),
        ("Does the following review have a positive or negative opinion of the movie?\n\n{sentence}\n{options_}", "{answer}"),
    ],
    "cola": [
        ("Sentence: \"{sentence}\"\nWould a linguist rate this sentence to be acceptable linguistically?\n\n{options_}", "{answer}"),
        ("{sentence}\n\nHow would you consider the linguistic integrity of the preceding sentence?\n{options_}", "{answer}"),
        ("Test sentence: \"{sentence}\"\nIs this test sentence a correct grammatical English sentence?\n\n{options_}", "{answer}"),
        ("Sentence: \"{sentence}\"\nWould a linguist rate this sentence to be acceptable linguistically?\n\n{options_}", "{answer}"),
        ("Is the following sentence linguistically acceptable?\n{sentence}\n{options_}", "{answer}"),
        ("Would the following sentence, by the strictest standards, be considered correct by a linguist?\n\n{sentence}\n{options_}", "{answer}"),
        ("Is the next sentence syntactically and semantically acceptable?\n\n{sentence}\n{options_}", "{answer}"),
        ("Would a linguist find the following sentence to be a valid English sentence grammatically?\n\n{sentence}\n{options_}", "{answer}"),
    ],
    "mrpc": [
        ("Here are two sentences:\n{sentence1}\n{sentence2}\nDo they have the same meaning?\n{options_}", "{answer}"),
        ("Here are two sentences:\n\n{sentence1}\n\n{sentence2}\nAre the two sentences saying the same thing?\n{options_}", "{answer}"),
        ("{sentence1}\n\n{sentence2}\n\nDo the above sentences mean the same thing?\n{options_}", "{answer}"),
        ("{sentence1}\n\n{sentence2}\n\nPlease tell me if the sentences above mean the same.\n{options_}", "{answer}"),
        ("{sentence1}\n{sentence2}\nAre these sentences conveying the same meaning?\n{options_}", "{answer}"),
        ("{sentence1}\n{sentence2}\nIf the first sentence is true, is the second one also true?\n{options_}", "{answer}"),
        ("{sentence1}\n{sentence2}\nAre these two sentences paraphrases of each other?\n{options_}", "{answer}"),
        ("Do the following two sentences have the same meaning?\n{sentence1}\n{sentence2}\n\n{options_}", "{answer}"),
        ("Do these two sentences mean the same thing?\n{sentence1}\n{sentence2}\n\n{options_}", "{answer}"),
        ("Do these sentences have the same meaning?\n{sentence1}\n{sentence2}\n\n{options_}", "{answer}"),
    ],
    "qqp": [
        ("{question1}\n{question2}\nWould you say that these questions are the same?\n{options_}", "{answer}"),
        ("{question1}\n{question2}\nDo those questions have the same meaning?\n{options_}", "{answer}"),
        ("{question1}\n{question2}\n\nAre these two questions inquiring about the same information?\n{options_}", "{answer}"),
        ("{question1}\n\n{question2}\n\nPlease tell me if those questions are the same.\n{options_}", "{answer}"),
        ("{question1}\n\n{question2}\n\nAre these two questions paraphrases of each other?\n{options_}", "{answer}"),
        ("First question: {question1}\nSecond question: {question2}\nAre these two questions asking the same thing?\n{options_}", "{answer}"),
        ("Question 1: {question1}\nQuestion 2: {question2}\nAre questions 1 and 2 asking the same thing?\n{options_}", "{answer}"),
        ("Question 1: {question1}\nQuestion 2: {question2}\n\nWould the answer to these two questions be the same?\n{options_}", "{answer}"),
        ("Are the following two questions the same?\n{question1}\n{question2}\n\n{options_}", "{answer}"),
        ("Do these questions have the same meaning?\n{question1}\n{question2}\n\n{options_}", "{answer}"),
    ],
    "mnli": [
        ("Premise: {premise}\n\nHypothesis: {hypothesis}\n\nDoes the premise entail the hypothesis?\n\n{options_}", "{answer}"),
        ("Premise: {premise}\nHypothesis: {hypothesis}\nIs the hypothesis entailed by the premise?\n{options_}", "{answer}"),
        ("Here is a premise:\n{premise}\n\nHere is a hypothesis:\n{hypothesis}\n\nIs it possible to conclude that if the premise is true, then so is the hypothesis?\n{options_}", "{answer}"),
        ("Sentence 1: {premise}\n\nSentence 2: {hypothesis}\nIs this second sentence entailed by the first sentence?\n\n{options_}", "{answer}"),
        ("Sentence 1: {premise}\n\nSentence 2: {hypothesis}\n\nIf the first sentence is true, then is the second sentence true?\n{options_}", "{answer}"),
        ("Based on the premise \"{premise}\", can we conclude the hypothesis \"{hypothesis}\" is true?\n\n{options_}", "{answer}"),
        ("Premise: \"{premise}\" If this premise is true, what does that tell us about whether it entails the hypothesis \"{hypothesis}\"?\n\n{options_}", "{answer}"),
        ("Premise:\n\"{premise}\" Based on this premise, is the hypothesis \"{hypothesis}\" true?\n{options_}", "{answer}"),
        ("If {premise}, can we conclude that \"{hypothesis}\"?\n{options_}", "{answer}"),
        ("{premise}\n\nDoes it follow that \"{hypothesis}\"?\n{options_}", "{answer}"),
    ],
    "qnli": [
        ("Does the sentence \"{sentence}\" answer the question \"{question}\"\n\n{options_}", "{answer}"),
        ("Does the sentence \"{sentence}\" provide a valid answer to the question \"{question}\"\n{options_}", "{answer}"),
        ("Is \"{sentence}\" a good answer to the question \"{question}\"\n{options_}", "{answer}"),
        ("Does \"{sentence}\" correctly answer the question of {question}\n{options_}", "{answer}"),
        ("Does \"{sentence}\" contain the correct answer to \"{question}\"\n{options_}", "{answer}"),
        ("Q: {question}\n A: {sentence}\n Does the answer correctly answer the question\n\n{options_}", "{answer}"),
        ("Question: {question}\nAnswer: {sentence}\n Is the question answered in a satisfactory fashion?\n\n{options_}", "{answer}"),
        ("Question: {question}\n\nIs {sentence} a good answer to this question?\n\n{options_}", "{answer}"),
        ("Question: {question}\n\nIs \"{sentence}\" the correct answer?\n\n{options_}", "{answer}"),
    ],
    "rte": [
        ("{premise}\n\nBased on the paragraph above can we conclude that \"{hypothesis}\"?\n\n{options_}", "{answer}"),
        ("{premise}\n\nBased on that paragraph can we conclude that this sentence is true?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{premise}\n\nCan we draw the following conclusion?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{premise}\nDoes this next sentence follow, given the preceding text?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{premise}\nCan we infer the following?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("Read the following paragraph and determine if the hypothesis is true:\n\n{premise}\n\nHypothesis: {hypothesis}\n\n{options_}", "{answer}"),
        ("Read the text and determine if the sentence is true:\n\n{premise}\n\nSentence: {hypothesis}\n\n{options_}", "{answer}"),
        ("Can we draw the following hypothesis from the context? \n\nContext:\n\n{premise}\n\nHypothesis: {hypothesis}\n\n{options_}", "{answer}"),
        ("Determine if the sentence is true based on the text below:\n{hypothesis}\n\n{premise}\n{options_}", "{answer}"),
    ],
    "cb": [
        ("{premise}\n\nBased on the paragraph above can we conclude that \"{hypothesis}\"?\n\n{options_}", "{answer}"),
        ("{premise}\n\nBased on that paragraph can we conclude that this sentence is true?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{premise}\n\nCan we draw the following conclusion?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{premise}\nDoes this next sentence follow, given the preceding text?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{premise}\nCan we infer the following?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("Read the following paragraph and determine if the hypothesis is true:\n\n{premise}\n\nHypothesis: {hypothesis}\n\n{options_}", "{answer}"),
        ("Read the text and determine if the sentence is true:\n\n{premise}\n\nSentence: {hypothesis}\n\n{options_}", "{answer}"),
        ("Can we draw the following hypothesis from the context? \n\nContext:\n\n{premise}\n\nHypothesis: {hypothesis}\n\n{options_}", "{answer}"),
        ("Determine if the sentence is true based on the text below:\n{hypothesis}\n\n{premise}\n{options_}", "{answer}"),
    ],
    "copa": [
        ("{premise} What is the {question}?\n\n{options_}", "{answer}"),
        ("Here is a premise:{premise}\n\nWhat is the {question}?\n\n{options_}", "{answer}"),
        ("{premise}\n\nWhat is the {question} of the preceding sentence?\n\n{options_}", "{answer}"),
        ("{premise}\n\nWhat is a plausible {question}?\n\n{options_}", "{answer}"),
        ("Based on the following sentence, what is the {question}?\n\n{premise}\n\n{options_}", "{answer}"),
        ("{premise}\n\n{question}: \n\n{options_}", "{answer}"),
        ("What is the {question} of the following sentence?\n\n{premise}\n\n{options_}", "{answer}"),
        ("Answer the following question about this sentence:\n\n{premise}\n\nWhat is the {question}?\n\n{options_}", "{answer}"),
        ("{glm_premise}\n\n{options_}", "{answer}"),
    ],
    "boolq": [
        ("{text}\n\nCan we conclude that {question}?\n\n{options_}", "{answer}"),
        ("{text}\n\nIs it true that {question}?\n\n{options_}", "{answer}"),
        ("{text}\n\n{question}?\n\n{options_}", "{answer}"),
        ("Text: {text}\n\nQuestion: {question}?\n\n{options_}", "{answer}"),
        ("{text}\n\nWhat's the best answer to this question: {question}?\n\n{options_}", "{answer}"),
        ("{text}\nBased on the above text, what's the best answer to this question: {question}?\n\n{options_}", "{answer}"),
        ("{text}\nAnswer this question, making sure that the answer is supposed by the text: {question}?\n\n{options_}", "{answer}"),
        ("{text}\n\nIs the following statement correct based on the text\n\n{question}\n\n{options_}", "{answer}"),
        ("Is it true that {question} based on the following text?\n\n{text}\n\n{options_}", "{answer}"),
    ],
    "multirc": [
        ("{paragraph}\n\nQuestion: \"{question}\"\n\nResponse: \"{response}\"\n\nDoes the response correctly answer the question?\n\n{options_}", "{answer}"),
        ("{paragraph}\n\nQuestion: \"{question}\"\n\nResponse: \"{response}\"\n\nBased on the paragraph, is the response to the question is factually correct?\n\n{options_}", "{answer}"),
        ("{paragraph}\n\nQuestion: \"{question}\"\n\nAnswer: \"{response}\"\n\nIs this answer correct?\n\n{options_}", "{answer}"),
        ("Paragraph: {paragraph}\n\nQuestion: \"{question}\"\n\nAnswer: \"{response}\"\n\nBased on the paragraph, is this answer correct\n\n{options_}", "{answer}"),
        ("{paragraph}\n\nBased on the paragraph, does the response \"{response}\" correctly answer the question \"{question}\"?\n\n{options_}", "{answer}"),
        ("{paragraph}\n\nAccording to the above paragraph, the correct answer to the question \"{question}\" is \"{response}\"?\n\n{options_}", "{answer}"),
        ("{paragraph}\n\nAfter reading the above, is \"{response}\" the correct answer to the question \"{question}\"?\n\n{options_}", "{answer}"),
        ("{paragraph}\n\nQuestion: \"{question}\"\n\nAnswer: \"{response}\"\n\nIs this answer to the question correct?\n{options_}", "{answer}"),
    ],
     "wic": [
        ("{sentence1}\n{sentence2}\nDoes the word \"{word}\" mean the same thing in the above two sentences?\n{options_}", "{answer}"),
        ("Sentence 1: {sentence1}\nSentence 2: {sentence2}\nDoes {word} mean the same thing in these two sentences?\n{options_}", "{answer}"),
        ("Here is one sentence: {sentence1}\nHere is another sentence: {sentence2}\nDoes the term {word} mean the same thing in both these sentences?\n{options_}", "{answer}"),
        ("In these two sentences (1) {sentence1} (2) {sentence2}, does the word {word} mean the same thing?\n{options_}", "{answer}"),
        ("Does word \"{word}\" have the same meaning in the following two sentences?\n\n{sentence1}\n\n{sentence2}\n\n{options_}", "{answer}"),
        ("Is the word \"{word}\" used in the same way in the following two sentences?\n\n{sentence1}\n\n{sentence2}\n\n{options_}", "{answer}"),
        ("Does the word \"{word}\" have the same definition in the next two sentences?\n\n{sentence1}\n\n{sentence2}\n\n{options_}", "{answer}"),
        ("Is {word} used to mean the same thing in the next two sentences?\n\n{sentence1}\n\n{sentence2}\n\n{options_}", "{answer}"),
        ("Does \"{word}\" mean the same thing in these two sentences?\n\n{sentence1}\n\n{sentence2}\n\n{options_}", "{answer}"),
        ("Does the word \"{word}\" mean the same thing in \"{sentence1}\" and \"{sentence2}\"?\n{options_}", "{answer}"),
    ],
    "wsc": [
        ("{context}\n\nAre \"{text1}\" and \"{text2}\" the same entity?\n\n{options_}", "{answer}"),
        ("{context}\n\nDo \"{text1}\" and \"{text2}\" have the same meaning?\n\n{options_}", "{answer}"),
        ("Given the following context\n\n{context}\n\nAre \"{text1}\" and \"{text2}\" the same?\n\n{options_}", "{answer}"),
        ("{context}\n\nDo \"{text2}\" and \"{text1}\" mean the same thing?\n\n{options_}", "{answer}"),
        ("{context}\n\nAre \"{text2}\" and \"{text1}\" the same thing in the aforementioned sentence?\n\n{options_}", "{answer}"),
        ("Context:{context}\n\nIs \"{text2}\" the same as \"{text1}\"?\n\n{options_}", "{answer}"),
        ("Consider this sentence: {context}\n\nAre \"{text2}\" and \"{text1}\" the same?\n\n{options_}", "{answer}"),
        ("Are \"{text1}\" and \"{text2}\" the same in this sentence?\n{context}\n\n{options_}", "{answer}"),
        ("Is \"{text1}\" the same as \"{text2}\" in this sentence?\n{context}\n\n{options_}", "{answer}"),
        ("Do \"{text1}\" and \"{text2}\" point to the same thing in the following sentence?\n\n{context}\n\n{options_}", "{answer}"),
    ],
    "anli": [
        ("{context}\n\nBased on the paragraph above can we conclude that \"{hypothesis}\"?\n\n{options_}", "{answer}"),
        ("{context}\n\nBased on that paragraph can we conclude that this sentence is true?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{context}\n\nCan we draw the following conclusion?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{context}\nDoes this next sentence follow, given the preceding text?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("{context}\nCan we infer the following?\n{hypothesis}\n\n{options_}", "{answer}"),
        ("Read the following paragraph and determine if the hypothesis is true:\n\n{context}\n\nHypothesis: {hypothesis}n\n{options_}", "{answer}"),
        ("Read the text and determine if the sentence is true:\n\n{context}\n\nSentence: {hypothesis}n\n{options_}", "{answer}"),
        ("Can we draw the following hypothesis from the context? \n\nContext:\n\n{context}\n\nHypothesis: {hypothesis}n\n{options_}", "{answer}"),
        ("Determine if the sentence is true based on the text below:\n{hypothesis}\n\n{context}\n{options_}", "{answer}"),
    ],
    "record": [
        ("Complete the passage.\n\n{passage}\n\n{query}\n\n{options_str}", "{answer}"),
        ("{passage}\n\n{query}\n\n{options_str}", "{answer}"),
        ("Find the right ending to this passage.\n\n{passage}\n\n{query}\n\n{options_str}", "{answer}"),
        ("What's the most logical way to complete this passage?\n\n{passage}\n\n{query}\n\n{options_str}", "{answer}"),
        ("Write the next sentence.\n\n{passage}\n\n{query}\n\n{options_str}", "{answer}"),
        ("How does this story end?\n\n{passage}\n\n{query}\n\n{options_str}", "{answer}"),
        ("Write the last sentence in this story.\n\n{passage}\n\n{query}\n\n{options_str}", "{answer}"),
        ("Compose the next sentence for this paragraph.\n\n{passage}\n\n{query}\n\n{options_str}", "{answer}"),
        ("What is the most logical completion of this news story?.\n\n{passage}\n\n{query}\n\n{options_str}", "{answer}"),
        ("How does the sentence end?\n\n{passage}\n\n{query}\n\n{options_str}", "{answer}"),
    ],
    "siqa": [
        ("{context} {question}\n\n{options_}", "{answer}"),
        ("Question: {context} {question}\n\nAnswer:\n{options_}", "{answer}"),
        ("Question: {context} {question}\n\nWhat is the correct answer to the question from the following choices?\n{options_}", "{answer}"),
        ("Q: {context} {question}\nWhat is the correct answer to this question?\n{options_}", "{answer}"),
        ("What is the answer?\n\n{context} {question}\n\n{options_}", "{answer}"),
        ("Answer the question\n\n{context} {question}\n\n{options_}", "{answer}"),
        ("{context} {question}\n\nPick the answer from these options\n\n{options_}", "{answer}"),
    ],
    "gsm8k": [
        ("{question}", "{answer}"),
        ("Question: {question}\n\nAnswer:", "{answer}"),
        ("Question: {question}\n\nWhat is the correct answer to the question?", "{answer}"),
        ("Q: {question}\nWhat is the correct answer to this question?", "{answer}"),
        ("What is the answer?\n\n{question}", "{answer}"),
        ("Answer the question\n\n{question}", "{answer}"),
    ],
    "hellaswag": [
        ("What happens next in this paragraph?\n\n{context}\n{options_}", "{answer}"),
        ("Continue writing the next sentence in this paragraph:\n\n{context}\n\n{options_}", "{answer}"),
        ("Continue writing the next sentence.\n\n{context}\n\n{options_}", "{answer}"),
        ("This is a test of commonsense. Complete the next sentence:\n\n{context}\n\n{options_}", "{answer}"),
        ("Write the next sentence in this paragraph:\n\n{context}\n\n{options_}", "{answer}"),
        ("How does the next paragraph end?\n\n{context}\n\n{options_}", "{answer}"),
        ("What most naturally follows?\n\n{context}\n\n{options_}", "{answer}"),
        ("What happens next?\n\n{context}\n\n{options_}", "{answer}"),
        ("What is the most logical next event?\n\n{context}\n\n{options_}", "{answer}"),
        ("Write the next sentence in the following story.\n\n{context}\n\n{options_}", "{answer}"),
    ],
    "winogrande": [
        ("How does the sentence end?\n\n{context}\n\n{options_}", "{answer}"),
        ("Write the next sentence.\n\n{context}\n\n{options_}", "{answer}"),
        ("Continue the following story.\n\n{context}\n\n{options_}", "{answer}"),
        ("Complete the following sentence.\n\n{context}\n\n{options_}", "{answer}"),
        ("Continue writing the following text.\n\n{context}\n\n{options_}", "{answer}"),
        ("How does the sentence end?\n\n{context}", "{answer}"),
        ("Write the next sentence.\n\n{context}", "{answer}"),
        ("Continue the following story.\n\n{context}", "{answer}"),
        ("Complete the following sentence.\n\n{context}", "{answer}"),
        ("Continue writing the following text.\n\n{context}", "{answer}"),
    ],
    "logiqa": [
        ("Passage: {context}\nQuestion: {question}\n\n{options_}\nAnswer:", "{answer}"),
        ("Read the following context and determine which answer is correct:\n\n{context}\nQuestion: {question}\n\n{options_}", "{answer}"),
        ("Read the text and determine which answer is true:\n\n{context}\nQuestion: {question}\n\n{options_}", "{answer}"),
        ("{context}\nQuestion: {question}\n\n{options_}Answer:\n", "{answer}"),
        ("{context}\nQuestion: {question}\n\nWhat is the correct answer to the question from the following choices?\n{options_}", "{answer}"),
        ("{context}\nQ: {question}\nWhat is the correct answer to this question?\n{options_}", "{answer}"),
        ("{context}\nWhat is the answer?\n\n {question}\n\n{options_}", "{answer}"),
        ("Answer the question\n\n{context} {question}\n\n{options_}", "{answer}"),
        ("{context} {question}\n\nPick the answer from these options\n\n{options_}", "{answer}"),
    ],
    "sciq": [
        ("{support}\n{question}\n\n{options_}", "{answer}"),
        ("Read this supporting material: \"{support}\"\n\nNow answer this question: \"{question}\"\n\n{options_}\nAnswer:", "{answer}"),
        ("Given the supporting material \"{support}\", what is the answer to the question or completion \"{question}\"\n\n{options_}", "{answer}"),
        ("Knowing that \"{support}\", how would one answer \"{question}\"\n\n{options_}", "{answer}"),
        ("Use evidence from the supporting material that {support} to answer this question: \"{question}\"\n\n{options_}", "{answer}"),
        ("Supporting material: {support}\nQuestion: {question}\n\n{options_}What's the answer?", "{answer}"),
        ("Use this supporting material to answer the question: {support}\n\n{question}\n\n{options_}", "{answer}"),
    ],
    "triviaqa": [
        ("Please answer this question: {question}", "{answer}"),
        ("{question}", "{answer}"),
        ("Write the answer: {question}", "{answer}"),
        ("What is the answer: {question}", "{answer}"),
        ("Answer this question.\n\n{question}", "{answer}"),
        ("Answer the following question. {question}", "{answer}"),
        ("Question: {question}\nAnswer:", "{answer}"),
        ("{question}???", "{answer}"),
        ("Trivia question: {question}\nAnd the answer is?", "{answer}"),
        ("{question}\nWhat is the answer?", "{answer}"),
    ],
}

PATTERNS_NO_OPTIONS = {
    "arc": [
        ("{question}", "{answer}"),
        ("Question: {question}\nAnswer:", "{answer}"),
        ("Q: {question}\nA:", "{answer}"),
        ("Q: {question}\nWhat is the correct answer to this question?", "{answer}"),
        ("What is the answer?\n{question}", "{answer}"),
        ("Answer the question\n{question}", "{answer}"),
        ("Answer this:\n{question}", "{answer}"),
        ("Provide the correct response:\n{question}", "{answer}"),
        ("{question}\nReply:", "{answer}"),
        ("What is the answer to: {question}", "{answer}"),
    ],
    "rte": [
        ("{premise}\n\nBased on the paragraph above can we conclude that \"{hypothesis}\"?", "{answer}"),
        ("{premise}\n\nBased on that paragraph can we conclude that this sentence is true?\n{hypothesis}", "{answer}"),
        ("{premise}\n\nCan we draw the following conclusion?\n{hypothesis}", "{answer}"),
        ("{premise}\nDoes this next sentence follow, given the preceding text?\n{hypothesis}", "{answer}"),
        ("{premise}\nCan we infer the following?\n{hypothesis}", "{answer}"),
        ("Read the following paragraph and determine if the hypothesis is true:\n\n{premise}\n\nHypothesis: {hypothesis}", "{answer}"),
        ("Read the text and determine if the sentence is true:\n\n{premise}\n\nSentence: {hypothesis}", "{answer}"),
        ("Can we draw the following hypothesis from the context? \n\nContext:\n\n{premise}\n\nHypothesis: {hypothesis}", "{answer}"),
        ("Determine if the sentence is true based on the text below:\n{hypothesis}\n\n{premise}", "{answer}"),
    ],
    "boolq": [
        ("{text}\n\nCan we conclude that {question}?", "{answer}"),
        ("{text}\n\nIs it true that {question}?", "{answer}"),
        ("{text}\n\n{question}?", "{answer}"),
        ("Text: {text}\n\nQuestion: {question}?", "{answer}"),
        ("{text}\n\nWhat's the best answer to this question: {question}?", "{answer}"),
        ("{text}\nBased on the above text, what's the best answer to this question: {question}?", "{answer}"),
        ("{text}\nAnswer this question, making sure that the answer is supposed by the text: {question}?", "{answer}"),
        ("{text}\n\nIs the following statement correct based on the text\n\n{question}", "{answer}"),
        ("Is it true that {question} based on the following text?\n\n{text}", "{answer}"),
    ],
    "hellaswag": [
        ("What happens next in this paragraph?\n\n{context}", "{answer}"),
        ("Continue writing the next sentence in this paragraph:\n\n{context}", "{answer}"),
        ("Continue writing the next sentence.\n\n{context}", "{answer}"),
        ("This is a test of commonsense. Complete the next sentence:\n\n{context}", "{answer}"),
        ("Write the next sentence in this paragraph:\n\n{context}", "{answer}"),
        ("How does the next paragraph end?\n\n{context}", "{answer}"),
        ("What most naturally follows?\n\n{context}", "{answer}"),
        ("What happens next?\n\n{context}", "{answer}"),
        ("What is the most logical next event?\n\n{context}", "{answer}"),
        ("Write the next sentence in the following story.\n\n{context}", "{answer}"),
    ],
    "winogrande": [
        ("How does the sentence end?\n\n{context}", "{answer}"),
        ("Write the next sentence.\n\n{context}", "{answer}"),
        ("Continue the following story.\n\n{context}", "{answer}"),
        ("Complete the following sentence.\n\n{context}", "{answer}"),
        ("Continue writing the following text.\n\n{context}", "{answer}"),
    ],
    "openbookqa": [
        ("{question}", "{answer}"),
        ("Read this fact\n\nNow answer this question: \"{question}\"", "{answer}"),
        ("Given the fact, what is the answer to the question or completion \"{question}\"", "{answer}"),
        ("Knowing that fact, how would one answer \"{question}\"", "{answer}"),
        ("Use evidence from the fact to answer this question: \"{question}\"", "{answer}"),
        ("Question: {question}\n\nWhat's the answer?", "{answer}"),
        ("Use this fact to answer the question:\n\n{question}", "{answer}"),
    ],
    "piqa": [
        ("Here is a goal: {goal}\n\nHow would you accomplish this goal?", "{answer}"),
        ("Here is a goal: {goal}\n\nWhich way makes more sense to accomplish this goal?", "{answer}"),
        ("Goal: {goal}\n\nWhich of the methods is more reasonable for accomplishing this goal?", "{answer}"),
        ("Objective: {goal}\n\nWhich of the solutions is more sound in terms of naive physics reasoning?", "{answer}"),
        ("How do you do this: {goal}", "{answer}"),
        ("What is the best way to: {goal}", "{answer}"),
        ("Which of the solutions is better for the following goal:\n{goal}", "{answer}"),
        ("How would someone go about accomplishing this goal?\n{goal}", "{answer}"),
    ],
    "copa": [
        ("{premise} What is the {question}?", "{answer}"),
        ("Here is a premise: {premise}\n\nWhat is the {question}?", "{answer}"),
        ("{premise}\n\nWhat is the {question} of the preceding sentence?", "{answer}"),
        ("{premise}\n\nWhat is a plausible {question}?", "{answer}"),
        ("Based on the following sentence, what is the {question}?\n\n{premise}", "{answer}"),
        ("{premise}\n\n{question}: ", "{answer}"),
        ("What is the {question} of the following sentence?\n\n{premise}", "{answer}"),
        ("Answer the following question about this sentence:\n\n{premise}\n\nWhat is the {question}?", "{answer}"),
        ("{glm_premise}", "{answer}"),
    ],
    "multirc": [
        ("READING COMPREHENSION ANSWER KEY\n{paragraph}\n\n{question}", "[{glm_answer}] {response}"),
        ("{paragraph}\nQuestion: {question}\nAnswer: ", "{response}\nIs the answer correct? {answer}"),
        ("{paragraph}\n\nQuestion: \"{question}\"\n\nResponse: ", "\"{response}\"\n\nDoes the response correctly answer the question? {answer}"),
        ("{paragraph}\n\nQuestion: \"{question}\"\n\nResponse: ", "\"{response}\"\n\nBased on the paragraph, is the response to the question is factually correct? {answer}"),
        ("{paragraph}\n\nQuestion: \"{question}\"\n\nAnswer: ", "\"{response}\"\n\nIs this answer correct? {answer}"),
        ("Paragraph: {paragraph}\n\nQuestion: \"{question}\"\n\nAnswer: ", "\"{response}\"\n\nBased on the paragraph, is this answer correct? {answer}"),
        ("{paragraph}\n\nQuestion: \"{question}\"\n\nAnswer: ", "\"{response}\"\n\nIs this answer to the question correct? {answer}"),
    ],
    "record": [
        ("Complete the passage.\n\n{passage}\n\n{query}", "{answer}"),
        ("{passage}\n\n{query}", "{answer}"),
        ("Find the right ending to this passage.\n\n{passage}\n\n{query}", "{answer}"),
        ("What's the most logical way to complete this passage?\n\n{passage}\n\n{query}", "{answer}"),
        ("Write the next sentence.\n\n{passage}\n\n{query}", "{answer}"),
        ("How does this story end?\n\n{passage}\n\n{query}", "{answer}"),
        ("Write the last sentence in this story.\n\n{passage}\n\n{query}", "{answer}"),
        ("Compose the next sentence for this paragraph.\n\n{passage}\n\n{query}", "{answer}"),
        ("What is the most logical completion of this news story?.\n\n{passage}\n\n{query}", "{answer}"),
        ("How does the sentence end?\n\n{passage}\n\n{query}", "{answer}"),
    ],
    "sciq": [
        ("{support}\n{question}", "{answer}"),
        ("Read this supporting material: \"{support}\"\n\nNow answer this question: \"{question}\"\nAnswer:", "{answer}"),
        ("Given the supporting material \"{support}\", what is the answer to the question or completion \"{question}\"", "{answer}"),
        ("Knowing that \"{support}\", how would one answer \"{question}\"", "{answer}"),
        ("Use evidence from the supporting material that {support} to answer this question: \"{question}\"", "{answer}"),
        ("Supporting material: {support}\nQuestion: {question}What's the answer?", "{answer}"),
        ("Use this supporting material to answer the question: {support}\n\n{question}", "{answer}"),
    ],
    "logiqa": [
        ("Passage: {context}\nQuestion: {question}\nAnswer:", "{answer}"),
        ("Read the following context and determine which answer is correct:\n\n{context}\nQuestion: {question}", "{answer}"),
        ("Read the text and determine which answer is true:\n\n{context}\nQuestion: {question}", "{answer}"),
        ("{context}\nQuestion: {question}Answer:\n", "{answer}"),
        ("{context}\nQuestion: {question}\n\nWhat is the correct answer to the question?", "{answer}"),
        ("{context}\nQ: {question}\nWhat is the correct answer to this question?", "{answer}"),
        ("{context}\nWhat is the answer?\n\n {question}", "{answer}"),
        ("Answer the question\n\n{context} {question}", "{answer}"),
    ],
    "siqa": [
        ("{context} {question}", "{answer}"),
        ("Question: {context} {question}\n\nAnswer:", "{answer}"),
        ("Question: {context} {question}\n\nWhat is the correct answer to the question?", "{answer}"),
        ("Q: {context} {question}\nWhat is the correct answer to this question?", "{answer}"),
        ("What is the answer?\n\n{context} {question}", "{answer}"),
        ("Answer the question\n\n{context} {question}", "{answer}"),
    ],
    "triviaqa": [
        ("Please answer this question: {question}", "{answer}"),
        ("{question}", "{answer}"),
        ("Write the answer: {question}", "{answer}"),
        ("What is the answer: {question}", "{answer}"),
        ("Answer this question.\n\n{question}", "{answer}"),
        ("Answer the following question. {question}", "{answer}"),
        ("Question: {question}\nAnswer:", "{answer}"),
        ("{question}???", "{answer}"),
        ("Trivia question: {question}\nAnd the answer is?", "{answer}"),
        ("{question}\nWhat is the answer?", "{answer}"),
    ],
    "race": [
        ("{article}\n\nPlease answer this question: {question}", "{answer}"),
        ("{article}\n\n{question}", "{answer}"),
        ("{article}\nQuestion: {question}\nAnswer:", "{answer}"),
        ("Article: {article}\nQuestion: {question}\nAnswer:", "{answer}"),
        ("{article}\nQ: {question}\n", "{answer}"),
        ("{article}\n\nWhat's the answer to this question: {question}?", "{answer}"),
        ("{article}\n\nWrite the answer: {question}", "{answer}"),
        ("{article}\nAnswer the following question. {question}", "{answer}"),
        ("{article}\n\n{question}\nWhat is the answer?", "{answer}"),
    ],
    "mrpc": [
        ("Here are two sentences:\n{sentence1}\n{sentence2}\nDo they have the same meaning?", "{answer}"),
        ("Here are two sentences:\n\n{sentence1}\n\n{sentence2}\nAre the two sentences saying the same thing?", "{answer}"),
        ("{sentence1}\n\n{sentence2}\n\nDo the above sentences mean the same thing?", "{answer}"),
        ("{sentence1}\n\n{sentence2}\n\nPlease tell me if the sentences above mean the same.", "{answer}"),
        ("{sentence1}\n{sentence2}\nAre these sentences conveying the same meaning?", "{answer}"),
        ("{sentence1}\n{sentence2}\nIf the first sentence is true, is the second one also true?", "{answer}"),
        ("{sentence1}\n{sentence2}\nAre these two sentences paraphrases of each other?", "{answer}"),
        ("Do the following two sentences have the same meaning?\n{sentence1}\n{sentence2}\n", "{answer}"),
        ("Do these two sentences mean the same thing?\n{sentence1}\n{sentence2}\n", "{answer}"),
        ("Do these sentences have the same meaning?\n{sentence1}\n{sentence2}\n", "{answer}"),
    ],
    "cola": [
        ("Sentence: \"{sentence}\"\nWould a linguist rate this sentence to be acceptable linguistically?", "{answer}"),
        ("{sentence}\n\nHow would you consider the linguistic integrity of the preceding sentence?", "{answer}"),
        ("Test sentence: \"{sentence}\"\nIs this test sentence a correct grammatical English sentence?", "{answer}"),
        ("Sentence: \"{sentence}\"\nWould a linguist rate this sentence to be acceptable linguistically?", "{answer}"),
        ("Is the following sentence linguistically acceptable?\n{sentence}", "{answer}"),
        ("Would the following sentence, by the strictest standards, be considered correct by a linguist?\n\n{sentence}", "{answer}"),
        ("Is the next sentence syntactically and semantically acceptable?\n\n{sentence}", "{answer}"),
        ("Would a linguist find the following sentence to be a valid English sentence grammatically?\n\n{sentence}", "{answer}"),
    ],
    "sst2": [
        ("Review:\n{sentence}\nIs this movie review sentence negative or positive?", "{answer}"),
        ("Short movie review: {sentence}\nDid the critic thinking positively or negatively of the movie?", "{answer}"),
        ("Sentence from a movie review: {sentence}\nWas the movie seen positively or negatively based on the preceding review?\n", "{answer}"),
        ("\"{sentence}\"\nHow would the sentiment of this sentence be perceived?\n", "{answer}"),
        ("Is the sentiment of the following sentence positive or negative?\n{sentence}", "{answer}"),
        ("What is the sentiment of the following movie review sentence?\n{sentence}", "{answer}"),
        ("Would the following phrase be considered positive or negative?\n\n{sentence}", "{answer}"),
        ("Does the following review have a positive or negative opinion of the movie?\n\n{sentence}", "{answer}"),
    ],
    "qnli": [
        ("Does the sentence \"{sentence}\" answer the question \"{question}\"", "{answer}"),
        ("Does the sentence \"{sentence}\" provide a valid answer to the question \"{question}\"", "{answer}"),
        ("Is \"{sentence}\" a good answer to the question \"{question}\"", "{answer}"),
        ("Does \"{sentence}\" correctly answer the question of {question}", "{answer}"),
        ("Does \"{sentence}\" contain the correct answer to \"{question}\"", "{answer}"),
        ("Q: {question}\n A: {sentence}\n Does the answer correctly answer the question", "{answer}"),
        ("Question: {question}\nAnswer: {sentence}\n Is the question answered in a satisfactory fashion?", "{answer}"),
        ("Question: {question}\n\nIs {sentence} a good answer to this question?", "{answer}"),
        ("Question: {question}\n\nIs \"{sentence}\" the correct answer?", "{answer}"),
    ],
    "bigbench_abstract_narrative_understanding": [
        ("{inputs}", "{answer}"),
    ],
    "bigbench_goal_step_wikihow": [
        ("{inputs}", "{answer}"),
    ],
    "bigbench_social_iqa": [
        ("{inputs}", "{answer}"),
        ("{inputs}\nWhat is the correct answer to this question?", "{answer}"),
        ("What is the answer?\n{inputs}", "{answer}"),
        ("Answer the question\n{inputs}", "{answer}"),
    ],
    "bigbench_timedial": [
        ("{inputs}", "{answer}"),
    ],
    "mmlu_professional_law": [
        ("Complete the passage.\n\n{question}", "{answer}"),
        ("{question}", "{answer}"),
        ("Find the right ending to this passage.\n\n{question}", "{answer}"),
        ("Write the next sentence.\n\n{question}", "{answer}"),
        ("Write the last sentence in this story.\n\n{question}", "{answer}"),
        ("What is the answer?\n{question}", "{answer}"),
        ("Answer the question\n{question}", "{answer}"),
        ("Read the following paragraph and answer the question:\n\n{question}", "{answer}"),
    ],
    "mmlu_high_school_world_history": [
        ("Please answer this question: {question}", "{answer}"),
        ("{question}", "{answer}"),
        ("Write the answer: {question}", "{answer}"),
        ("What is the answer: {question}", "{answer}"),
        ("Answer this question.\n\n{question}", "{answer}"),
        ("Answer the following question. {question}", "{answer}"),
        ("Given the passage, what is the answer to the question or completion \"{question}\"", "{answer}"),
        ("Use evidence from the passage to answer this question: \"{question}\"", "{answer}"),
    ],
    "mmlu_high_school_government_and_politics": [
        ("{question}", "{answer}"),
        ("Question: {question}\nAnswer:", "{answer}"),
        ("Q: {question}\nWhat is the correct answer to this question?", "{answer}"),
        ("What is the answer?\n{question}", "{answer}"),
        ("Answer the question\n{question}", "{answer}"),
    ],
    "mmlu_us_foreign_policy": [
        ("{question}", "{answer}"),
        ("Question: {question}\nAnswer:", "{answer}"),
        ("Q: {question}\nWhat is the correct answer to this question?", "{answer}"),
        ("What is the answer?\n{question}", "{answer}"),
        ("Answer the question\n{question}", "{answer}"),
    ],
    "mmlu_business_ethics": [
        ("{question}", "{answer}"),
        ("Question: {question}\nAnswer:", "{answer}"),
        ("Q: {question}\nWhat is the correct answer to this question?", "{answer}"),
        ("What is the answer?\n{question}", "{answer}"),
        ("Answer the question\n{question}", "{answer}"),
        ("Fill in the blanks in the questions\n{question}", "{answer}"),
        ("Complete the sentence\n{question}", "{answer}"),
    ],
    "mmlu_high_school_computer_science": [
        ("{question}", "{answer}"),
        ("Question: {question}\nAnswer:", "{answer}"),
        ("Q: {question}\nWhat is the correct answer to this question?", "{answer}"),
        ("What is the answer?\n{question}", "{answer}"),
        ("Answer the question\n{question}", "{answer}"),
    ],
    "mmlu_auxiliary_train": [
        ("{question}", "{answer}"),
        ("Question: {question}\nAnswer:", "{answer}"),
        ("Q: {question}\nWhat is the correct answer to this question?", "{answer}"),
        ("What is the answer?\n{question}", "{answer}"),
        ("Answer the question\n{question}", "{answer}"),
    ],
    "CodeAlpaca20K": [
        ("{question}", "{answer}"),
    ],
    "alpaca-cleaned": [
        ("{question}", "{answer}"),
    ],
}